### PR TITLE
Use the animated logo on the landing page

### PR DESCRIPTION
**Pull request by sandhose**
I published https://github.com/sandhose/prettier-animated-logo under `@sandhose/prettier-animated-logo`. 

Still, we need a way to copy/import the css from the package. I thought of simple symlinks ; even though it seems to work on my machine, theres no guarantee the package will be installed in the same place every time, and I don't think it would work across all platforms.

### CODE REVIEW

**Comment by orta** [comment]
🔥

**Comment by azz** [comment]
Maybe add a pre-build step to copy the css?

**Comment by j-f1** [comment]
Any update on this? I’d like to get the parent PR merged :)

**Comment by sandhose** [comment]
@j-f1: for now @azz used the static version of the logo, which is probably good enough.
I'll do a separate PR on the main repo after https://github.com/prettier/prettier/pull/3718 is merged

**Pull request closed without merging**
